scrape_configs:
- job_name: 'Oncall-metrics'
  scrape_interval: 15s
  static_configs:
    - targets: ['oncall:9080']
- job_name: 'Blackbox-ICMP'
  scrape_interval: 1m
  metrics_path: /probe
  params:
    module: [icmp]
  file_sd_configs:
    - files:
      - /etc/prometheus/targets.d/blackbox-icmp.yml
  relabel_configs:
    - source_labels: [__address__]
      target_label: __param_target
    - source_labels: [__param_target]
      target_label: instance
    - target_label: __address__
      replacement: blackbox:9115

- job_name: 'Blackbox-TCP'
  scrape_interval: 1m
  metrics_path: /probe
  params:
    module: [tcp_connect]
  file_sd_configs:
    - files:
      - /etc/prometheus/targets.d/blackbox-tcp.yml
  relabel_configs:
    - source_labels: [__address__]
      target_label: __param_target
    - source_labels: [__param_target]
      target_label: instance
    - target_label: __address__
      replacement: blackbox:9115

- job_name: 'Blackbox-HTTP'
  scrape_interval: 1m
  metrics_path: /probe
  params:
    module: [http_2xx]
  file_sd_configs:
    - files:
      - /etc/prometheus/targets.d/blackbox-http.yml
  relabel_configs:
    - source_labels: [__address__]
      target_label: __param_target
    - source_labels: [__param_target]
      target_label: instance
    - target_label: __address__
      replacement: blackbox:9115

- job_name: 'Node-Exporter'
  scrape_interval: 15s
  static_configs:
    - targets: ['node_exporter:9100']

- job_name: 'custom-exporter'
  scrape_interval: 15s
  static_configs:
    - targets: ['custom_exporter:9000']

- job_name: 'nginx-exporter'
  scrape_interval: 15s
  static_configs:
    - targets: ['nginx_exporter:9113']

alerting:
  alertmanagers:
  - static_configs:
    - targets: ['alertmanager:9093']

rule_files:
  - rules.yml